version: '3'
services:
    #API          
    expensetrackerapi:
        build: 
            dockerfile: Dockerfile.dev
            context: ./expensetrackerapi
        ports:
            - '8080:8080'    
        environment: 
            - REACT_APP_API_BASE_URL=http://localhost:8080/api/1.0 # need to remove.

    #UI        
    expensetrackerui:
        restart: always
        build:
            context: ./expensetrackerui
            dockerfile: Dockerfile
            args:
                REACT_APP_API_BASE_URL: http://localhost:8080/api/1.0
        ports:
            - '80:80'
        environment: 
            - REACT_APP_API_BASE_URL=http://localhost:8080/api/1.0
        restart: always
        depends_on:
                - expensetrackerapi