version: '3'
services:   
    expensetrackerui:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./expensetrackerui
        ports:
            - '3000:80'
    expensetrackerapi:
        build: 
            dockerfile: Dockerfile.dev
            context: ./expensetrackerapi
        ports:
            - '8080:8080'    
        environment: 
            - REACT_APP_API_BASE_URL=http://localhost:8080